//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.WindowsInstallerXml.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WixStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WixStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Tools.WindowsInstallerXml.VisualStudio.WixStrings", typeof(WixStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Project Files (*.wixproj);*.wixproj.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Files (*.wxs,*.wxi,*.wxl);*.wxs,*.wxi,*.wxl.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J8KPQCHMHKP9K8J1ICH1J8RAJDMJMEI1E2KZQ0CDE8D1I8ZCZHJAC3MMRMADRDDZCDAED1EPZCR0KRMQI0J9PHP1MRI8JHZEHKMCZ1C8I8DHPHE3EQIRQTMTK0P1HDI2.
        /// </summary>
        internal static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _300 {
            get {
                object obj = ResourceManager.GetObject("300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Reference Files (*.dll;*.wixlib)\0*.dll;*.wixlib\0WiX Extension Files (*.dll)\0*.dll\0WiX Library Files (*.wixlib)\0*.wixlib\0All Files (*.*)\0*.*\0\0.
        /// </summary>
        internal static string AddReferenceDialogFilter {
            get {
                return ResourceManager.GetString("AddReferenceDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add WiX Library Reference.
        /// </summary>
        internal static string AddReferenceDialogTitle {
            get {
                return ResourceManager.GetString("AddReferenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the service of type &apos;{0}&apos; from the environment. Please log this as a bug..
        /// </summary>
        internal static string CannotGetService {
            get {
                return ResourceManager.GetString("CannotGetService", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon MacroIcon {
            get {
                object obj = ResourceManager.GetObject("MacroIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer XML.
        /// </summary>
        internal static string OfficialName {
            get {
                return ResourceManager.GetString("OfficialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library (.wixlib).
        /// </summary>
        internal static string OutputTypeLibraryDisplayName {
            get {
                return ResourceManager.GetString("OutputTypeLibraryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module (.msm).
        /// </summary>
        internal static string OutputTypeModuleDisplayName {
            get {
                return ResourceManager.GetString("OutputTypeModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package (.msi).
        /// </summary>
        internal static string OutputTypePackageDisplayName {
            get {
                return ResourceManager.GetString("OutputTypePackageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votive 2005 - Windows Installer XML (WiX) Toolset, Version {0}
        ///Copyright © Microsoft Corporation. All rights reserved.
        ///Core WiX Team: Aaron Stebner, Bob Arnson, Fredrik Grohn, Joe Abbott, Justin Rockwood, Mike Holcomb, Peter Marcu, Rob Mensching, Scott Kurtzeborn
        ///Emeritus Members: Derek Cicerone, Reid Gustin, Robert Flaming
        ///Additional Contributors: Adam Stritzel, John Lyon-Smith.
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 3.0.
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Events.
        /// </summary>
        internal static string WixBuildEventsPropertyPageName {
            get {
                return ResourceManager.GetString("WixBuildEventsPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string WixBuildPropertyPageName {
            get {
                return ResourceManager.GetString("WixBuildPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        internal static string WixCompilerPropertyPageName {
            get {
                return ResourceManager.GetString("WixCompilerPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Extension Reference.
        /// </summary>
        internal static string WixExtensionReferenceProperties {
            get {
                return ResourceManager.GetString("WixExtensionReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the WiX extension..
        /// </summary>
        internal static string WixExtensionReferenceVersionDescription {
            get {
                return ResourceManager.GetString("WixExtensionReferenceVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string WixExtensionReferenceVersionDisplayName {
            get {
                return ResourceManager.GetString("WixExtensionReferenceVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian.
        /// </summary>
        internal static string WixLibrarianPropertyPageName {
            get {
                return ResourceManager.GetString("WixLibrarianPropertyPageName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WixLibraryProjectIcon {
            get {
                object obj = ResourceManager.GetObject("WixLibraryProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Library Reference.
        /// </summary>
        internal static string WixLibraryReferenceProperties {
            get {
                return ResourceManager.GetString("WixLibraryReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string WixLibraryReferencesFolderName {
            get {
                return ResourceManager.GetString("WixLibraryReferencesFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker.
        /// </summary>
        internal static string WixLinkerPropertyPageName {
            get {
                return ResourceManager.GetString("WixLinkerPropertyPageName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WixMergeModuleProjectIcon {
            get {
                object obj = ResourceManager.GetObject("WixMergeModuleProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon WixProjectIcon {
            get {
                object obj = ResourceManager.GetObject("WixProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
