//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildWell.BuildWellWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuildWellWCF.IBuildWellWCF")]
    public interface IBuildWellWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/SaveBuild", ReplyAction="http://tempuri.org/IBuildWellWCF/SaveBuildResponse")]
        int SaveBuild(string binaryRev, string log, string changeControl, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/AppendToBuildLog", ReplyAction="http://tempuri.org/IBuildWellWCF/AppendToBuildLogResponse")]
        int AppendToBuildLog(int id, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/UpdateBuildBinaryRevision", ReplyAction="http://tempuri.org/IBuildWellWCF/UpdateBuildBinaryRevisionResponse")]
        int UpdateBuildBinaryRevision(int id, string binaryRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/UpdateBuildDate", ReplyAction="http://tempuri.org/IBuildWellWCF/UpdateBuildDateResponse")]
        int UpdateBuildDate(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/UpdateBuildLog", ReplyAction="http://tempuri.org/IBuildWellWCF/UpdateBuildLogResponse")]
        int UpdateBuildLog(int id, string log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/UpdateBuildChangeControl", ReplyAction="http://tempuri.org/IBuildWellWCF/UpdateBuildChangeControlResponse")]
        int UpdateBuildChangeControl(int id, string cc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/UpdateBuildStatus", ReplyAction="http://tempuri.org/IBuildWellWCF/UpdateBuildStatusResponse")]
        int UpdateBuildStatus(int id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildWellWCF/AddBuildReference", ReplyAction="http://tempuri.org/IBuildWellWCF/AddBuildReferenceResponse")]
        void AddBuildReference(int id, string refBy, string repo, string rev, string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildWellWCFChannel : BuildWell.BuildWellWCF.IBuildWellWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuildWellWCFClient : System.ServiceModel.ClientBase<BuildWell.BuildWellWCF.IBuildWellWCF>, BuildWell.BuildWellWCF.IBuildWellWCF {
        
        public BuildWellWCFClient() {
        }
        
        public BuildWellWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuildWellWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildWellWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildWellWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveBuild(string binaryRev, string log, string changeControl, string status) {
            return base.Channel.SaveBuild(binaryRev, log, changeControl, status);
        }
        
        public int AppendToBuildLog(int id, string msg) {
            return base.Channel.AppendToBuildLog(id, msg);
        }
        
        public int UpdateBuildBinaryRevision(int id, string binaryRev) {
            return base.Channel.UpdateBuildBinaryRevision(id, binaryRev);
        }
        
        public int UpdateBuildDate(int id) {
            return base.Channel.UpdateBuildDate(id);
        }
        
        public int UpdateBuildLog(int id, string log) {
            return base.Channel.UpdateBuildLog(id, log);
        }
        
        public int UpdateBuildChangeControl(int id, string cc) {
            return base.Channel.UpdateBuildChangeControl(id, cc);
        }
        
        public int UpdateBuildStatus(int id, string status) {
            return base.Channel.UpdateBuildStatus(id, status);
        }
        
        public void AddBuildReference(int id, string refBy, string repo, string rev, string url) {
            base.Channel.AddBuildReference(id, refBy, repo, rev, url);
        }
    }
}
