//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildWellWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        public Build()
        {
            this.BuildSources = new HashSet<BuildSource>();
            this.Deployments = new HashSet<Deployment>();
        }
    
        public int Id { get; set; }
        public string ChangeControl { get; set; }
        public System.DateTime BuildDate { get; set; }
        public string Status { get; set; }
        public string BinaryRevision { get; set; }
        public string BuildLog { get; set; }
    
        public virtual ICollection<BuildSource> BuildSources { get; set; }
        public virtual ICollection<Deployment> Deployments { get; set; }
    }
}
